### ISSUE TITLE
code examples on main page is not readable

### ISSUE THREAD

**Issue by raspher** [webiny/website#136]
Closer to bottom of main page the code is not readable, black text on dark purple background seems to be horrible idea.

![image](https://user-images.githubusercontent.com/23345803/167491607-41929aaa-7919-4a8a-b111-3cbb79710f84.png)

**Comment by endymion1818** [comment]
Thank you @raspher for reporting this issue!

**Comment by endymion1818** [comment]
Just so we're clear, this is happening at the bottom of https://www.webiny.com
